#pragma once
#include "cocos2d.h"
using namespace cocos2d;

enum TEXTURETYPE
{
	TEX_COIN, TEX_S1WALL, TEX_S1ROOM, TEX_S1GENERAL
};

enum STATE
{
	IDLE, JUMP, DROP, WALK, SIT, SIT_SHOT, IDLE_JUMP, WALK_JUMP, WALK_SIT, IDLE_SIT, UP_LOOK, UP_READY,
	DOWN_LOOK, SHOT, NULL_STATE, GOUP_SHOT, UP_SHOT, GODW_SHOT, SIT_GRENADE, GRENADE
};

enum
{
	HGR_JUMP, HGS_JUMP, HG_RUN, HGS_STAND, HGD_NULL, INV_NULL, HG_STAND, HG_SHOT, HGU_READY, HG_LOOKUP, HG_LOOKDOWN,
	HG_DOWN, HGS_DOWN, HGW_DOWN, INVINCIBLE, SJ_LEG, R_LEG, S_LEG, JR_LEG, HGU_SHOT, SHOT_GOUP, SHOT_GODW, DW_GRENADE,
	HG_GRENADE
};																		   
																		   
enum DIRECTION 
{

	LEFT, RIGHT
};

enum WEAPON
{
	SHOTGUN, MACHINEGUN, NORMALGUN, TURRET_BULLET, W_GRENADE
};

enum BOXTYPE
{
	BOX_HERO, BOX_HEROBULLET, BOX_TEXTURE, WALL, BOX_BOSSBODY, BOX_BOSSLEFT, BOX_BOSSRIGHT, BOX_TURRET,
	BOX_ENEMYATTACK, NOTBOX, BOX_HEROGRENADE
};

enum S1TAG
{
	S1_BGA, S1_WALL, S1_ROOM, S1_HERO
};

enum ENEMYTYPE
{
	BOSS, TURRET
};

enum EFFECTTYPE
{
	TURRET_EFFECT, HG_EFFECT, S1WALL_DESTROY, GRENADE_EFFECT, 
	S1BOSSENGINE_EFFECT, S1BOSSATTACKREADY_EFFECT, S1BOSSATTACK_EFFECT, S1BOSSATTACKEND_EFFECT
};

struct VectorInformation
{
	CGPoint vec;
	float	distance;
};